import { Geist, Geist_Mono,Reddit_Sans_Condensed } from "next/font/google";
import "./globals.css";

const redditSans = Reddit_Sans_Condensed({
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Film Festival Navigation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${redditSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
